### ISSUE TITLE
Lecture Notes preview not working

### ISSUE THREAD

**Issue by enzohnnn** [ucsd-cse15l-f22/ucsd-cse15l-f22.github.io#1]
https://github.com/ucsd-cse15l-f22/ucsd-cse15l-f22.github.io/blob/a65e735c7ec84a6f475160d0912753091cbb28f0/_posts/weeks/2022-09-26-week1.md?plain=1#L80-L84

I have commented out a specific line in the website's markdown that allows for students to preview the lecture notes because when it is built through Jekyll it is giving me a "Forbidden Error 403". I followed what you did in the previous course offering's website code.

This is what I am getting:
<img width="678" alt="Screen Shot 2022-09-28 at 3 01 43 PM" src="https://user-images.githubusercontent.com/47432341/192896734-b58e4108-6b34-4e5c-891d-e7cd148ef2e1.png">

This is an example from the previous website and how it looked:
<img width="676" alt="Screen Shot 2022-09-28 at 3 00 38 PM" src="https://user-images.githubusercontent.com/47432341/192896583-c934f78c-2bda-4945-9431-a4a59a7ae7de.png">

The lines it is parsing through are under "notes" at the head of the page here:
https://github.com/ucsd-cse15l-f22/ucsd-cse15l-f22.github.io/blob/a65e735c7ec84a6f475160d0912753091cbb28f0/_posts/weeks/2022-09-26-week1.md?plain=1#L19-L23

Another link of the same file I've tried would give me this preview:
<img width="673" alt="Screen Shot 2022-09-28 at 3 14 41 PM" src="https://user-images.githubusercontent.com/47432341/192898333-9cec1d13-6393-446e-afc4-c26505913587.png">

I believe the error is because of the URL I am using to access the drive. I've tested the links through various means and the links are specifically "publically viewable for anyone with link". I thought the URL would work since I got a shareable link but it doesn't seem so. Maybe it has to do with the accessibility of that specific drive.

**Comment by jpolitz** [comment]
I think the links look a little different last year, right? These are copied from week 1. They have a different structure than what you showed (with the usp/sharing stuff)

```
    - name: "1pm Wednesday"
      url: "https://drive.google.com/file/d/17DV-JqmU0Kmdn2pMuLmm4Xx5Lqt24qyB"
    - name: "2pm Wednesday"
      url: "https://drive.google.com/file/d/1LP-nxyuE403uUeIb9N2Lvko5N3nk77HM"
    - name: "3pm Wednesday"
      url: "https://drive.google.com/file/d/1yrBmdDwZi1EhxEWRZ-L2LYENaSSlTSVm"
```

**Comment by jpolitz** [comment]
(Thanks for the writeup, I instantly understood at least what the issue is, even if I'm not 100% on the fix)

**Comment by enzohnnn** [comment]
> I think the links look a little different last year, right? These are copied from week 1. They have a different structure than what you showed (with the usp/sharing stuff)
> 
> ```
>     - name: "1pm Wednesday"
>       url: "https://drive.google.com/file/d/17DV-JqmU0Kmdn2pMuLmm4Xx5Lqt24qyB"
>     - name: "2pm Wednesday"
>       url: "https://drive.google.com/file/d/1LP-nxyuE403uUeIb9N2Lvko5N3nk77HM"
>     - name: "3pm Wednesday"
>       url: "https://drive.google.com/file/d/1yrBmdDwZi1EhxEWRZ-L2LYENaSSlTSVm"
> ```

Yeah, I noticed the links were slightly different but from the different methods, I tried getting a drive link I couldn't seem to replicate this same type of link. I'll look into it more.

**Comment by jpolitz** [comment]
Can you copy the IDs and create these links by typing them in directly?
Does that work? I think that's what I did.

**Comment by enzohnnn** [comment]
Oh I got it! Thanks for the assistance, I will push an update shortly.
